# Architecture
include(TargetArchitecture)
target_architecture(ARCHITECTURE)

#if("${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
#    message("=====> Detected 64 bit architecture")
#    set(TARGET_BITS 64)
#    set(ARCH_PREFIX "x64")
# else()
#    message("=====> Detected 32 bit architecture")
#    set(TARGET_BITS 32)
#    set(ARCH_PREFIX "x86")
#endif()

if(${ARCHITECTURE} MATCHES "x86_64")
    message("=====> Detected 64 bit architecture [${ARCHITECTURE}]")
    set(TARGET_BITS 64)
    set(ARCH_PREFIX "x64")
else()
    message("=====> Detected 32 bit architecture [${ARCHITECTURE}]")
    set(TARGET_BITS 32)
    set(ARCH_PREFIX "x86")
endif()
message("=====> TARGET_BITS: ${TARGET_BITS}")
