macro(set_base_vars)
    set_property(GLOBAL PROPERTY USE_FOLDERS ON)

    if(NOT CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE Release)
    endif()

    set(CMAKE_BINARY_DIR ${CMAKE_SOURCE_DIR})

    set(OUTPUT_DIR      ${ARCH_PREFIX}-${CMAKE_BUILD_TYPE})
    set(OUTPUT_DIR_MAIN ${CMAKE_BINARY_DIR}/_out/${OUTPUT_DIR})
    set(OUTPUT_DIR_ADD  ${CMAKE_BINARY_DIR}/_out/${OUTPUT_DIR})
    set(OUTPUT_DIR_INST ${CMAKE_BINARY_DIR}/_out/${OUTPUT_DIR}_install)
    set(CMAKE_INSTALL_PREFIX ${OUTPUT_DIR_INST})

    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE  ${OUTPUT_DIR_MAIN})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG    ${OUTPUT_DIR_MAIN})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE  ${OUTPUT_DIR_ADD})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG    ${OUTPUT_DIR_ADD})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE  ${OUTPUT_DIR_ADD})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG    ${OUTPUT_DIR_ADD})
    if(MSVC)
        # set(CMAKE_PDB_OUTPUT_DIRECTORY                  ${OUTPUT_DIR_ADD})
        set(CMAKE_COMPILE_PDB_OUTPUT_DIRECTORY_RELEASE  ${OUTPUT_DIR_ADD})
        set(CMAKE_COMPILE_PDB_OUTPUT_DIRECTORY_DEBUG    ${OUTPUT_DIR_ADD})
    endif()

    set(THIRDPARTY_LOCATION                              "${CMAKE_BINARY_DIR}/3rdparty")
endmacro()

