function(cmake_list_all_variables)
    MESSAGE("+++> ------------------------------ VARIABLES ------------------------------ ")
    get_cmake_property(_variableNames VARIABLES)
    list (REMOVE_DUPLICATES _varNames)
    list (SORT _varNames)
    foreach (_variableName ${_variableNames})
        message("+++> ${_variableName}=${${_variableName}}")
    endforeach()
    MESSAGE("+++> ----------------------------------------------------------------------- ")
endfunction()


function(cmake_list_all_init_variables)
    MESSAGE("+++> ------------------------------ INIT VARIABLES ------------------------- ")
    get_cmake_property(_varNames VARIABLES)
    list (REMOVE_DUPLICATES _varNames)
    list (SORT _varNames)
    foreach (_varName ${_varNames})
        if (_varName MATCHES "_INIT$")
            message("+++> ${_varName}=${${_varName}}")
        endif()
    endforeach()
    MESSAGE("+++> ----------------------------------------------------------------------- ")
endfunction()

function(cmake_get_cxx_compiler)
    MESSAGE("+++> ------------------------------ CXX COMPILER --------------------------- ")
    get_cmake_property(_varNames VARIABLES)
    list (REMOVE_DUPLICATES _varNames)
    list (SORT _varNames)
    foreach (_varName ${_varNames})
        if (_varName MATCHES "CMAKE_CXX_COMPILER$")
            message("+++> ${_varName}=${${_varName}}")
        endif()
    endforeach()
    MESSAGE("+++> ----------------------------------------------------------------------- ")
endfunction()

function(cmake_get_includes)
    MESSAGE("+++> ------------------------------ INCLUDES ------------------------------- ")
    get_cmake_property(_varNames VARIABLES)
    list (REMOVE_DUPLICATES _varNames)
    list (SORT _varNames)
    foreach (_varName ${_varNames})
        if (_varName MATCHES "INCLUDE")
            message("+++> ${_varName}=${${_varName}}")
        endif()
    endforeach()
    MESSAGE("+++> ----------------------------------------------------------------------- ")
endfunction()
